### ISSUE TITLE
Read-Only Key are not entitled to request from the interface 31305

### ISSUE THREAD

**Issue by jayabie** [fresns/fresns#10]
Trying to add post but receiving `Read-Only Key are not entitled to request from the interface 31305`

Also i made the groups and title mandatory, but the changes are not showing in the editor.
i don't know if this is related to the error 31305.

**Comment by jevantang** [comment]
Key Configuration: `Admin Panel > Clients > App Center > App Keys`
Editor Configuration:  `Admin Panel > Operations > Publish > Post > Editor Function Status`
