### ISSUE TITLE
浏览器安装了 simpRead 插件之后，登录状态访问会导致浏览器卡死

### ISSUE THREAD

**Issue by niefufeng** [fresns/fresns#12]
**Fresns Version**
Latest

**Describe the bug**
在浏览器安装了 simpRead 插件的情况下，访问 https://discuss.fresns.cn 然后登录，之后进行访问任何页面都会导致浏览器卡死30秒左右

**To Reproduce**
1. 安装 simpRead: https://chrome.google.com/webstore/detail/simpread-reader-view/ijllcpnolfcooahcekpamkbidhejabll?hl=en
2. 访问 https://discuss.fresns.cn 然后登录
3. 访问首页、帖子页或其它页面即可

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.4
 - Browser: Google Chrome
 - Version: 114

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jevantang** [comment]
你发错地方了，应该发这里 https://github.com/kenshin/simpread/issues

**Comment by niefufeng** [comment]
@jevantang 我两边都提了 issue
