### ISSUE TITLE
Docker compatible to server requirements

### ISSUE THREAD

**Issue by ife-adewunmi** [fresns/fresns#14]
**Is your feature request related to a problem? Please describe.**
A team of engineers with different server environments setup would have difficulties setting up or contributing to the project

**Describe the solution you'd like**
Add a docker file for easy setup in local and production environment

**Describe alternatives you've considered**

**Additional context**

**Comment by ife-adewunmi** [comment]
Hello @jevantang, what do you think about my proposal?

**Comment by jevantang** [comment]
Hi,
Want Fresns to add a Docker installation method?

**Comment by ife-adewunmi** [comment]
Yes, please

**Comment by jevantang** [comment]
If I were to do it, it would probably take two weeks before I could schedule it, so if you'd like to contribute, you're certainly very welcome and appreciated.

**Comment by ife-adewunmi** [comment]
I will gladly look into that.

I would like you to answer this, please:
Which services in the **Server Requirements** section should be the default?


Environment | Services
-- | --
Web ServerChoose any one | Nginx, Apache, Caddy, IIS
PHP Version | PHP 8.1 or greater
PHP Extensions | fileinfo
PHP Functions | symlink, proc_open, shell_exec, passthru
Package Manager | Composer 2.5 or greater
Database and VersionChoose any one | MySQL 5.7 ~ 8.x, MariaDB 10.3 ~ 11.x, PostgreSQL 11.x ~ 15.x, SQL Server 2016(13.x) ~ 2022(16.x), SQLite 3.9 or greater

**Comment by jevantang** [comment]
Here are my recommendations

Web Server: Nginx 1.25 (HTTP/3 support)
PHP Version: 8.2
PHP Extensions: fileinfo, opcache
PHP Functions: symlink, proc_open, shell_exec (passthru can be temporarily enabled when using automatic Fresns upgrade.)
Package Manager: composer 2.5.8 (use the latest version)

Database:
The databases are not placed in the same docker, so users can install the databases separately.

**Comment by ife-adewunmi** [comment]
@jevantang 
I opened a PR for this
https://github.com/fresns/fresns/pull/22

**Comment by jevantang** [comment]
> @jevantang I opened a PR for this #22

Thank you, I'll take a look at it later.
