### ISSUE TITLE
fontawesome 图标对齐问题

### ISSUE THREAD

**Issue by tony-studio** [fresns/fresns#17]
![20230817154221](https://github.com/fresns/fresns/assets/60637421/5529624f-c248-401c-bf29-b22793f6f914)

PC web 左侧菜单的图标对齐存在问题，影响美观。
解决办法：li.nav-item > a.nav-link >i.fa-regular：class 中添加 “fa-fw” 即可。

![20230817155036](https://github.com/fresns/fresns/assets/60637421/30e17104-97bf-4d1f-8a21-9bcd2e5e96fe)

**Comment by jevantang** [comment]
感谢反馈，我还没注意有这个方法，已经应用在主题里，一会主题发个新版。

**Comment by jevantang** [comment]
已经采用 https://github.com/fresns/themes/commit/7ebb40b3ddd3296778b589ff8b6910d77b3e3308
