### ISSUE TITLE
3.0 政策设置->政策内容 支持1下变量

### ISSUE THREAD

**Issue by Naruto2018** [fresns/fresns#19]
建议 政策设置->政策内容 支持1下变量，因为内容涉及到网站名称，管理员联系 用变量更为方便

**Comment by jevantang** [comment]
这个建议不采纳。

服务协议和隐私政策，这些条款是需要人工去逐条确认的，非常不建议用程序去做模板和变量引用。因为这样做了之后，容易造成偷懒行为。在这件事上不能偷懒，否则容易留下隐患，在法律严格的国家，可能还有被告的风险。
