### ISSUE TITLE
不为别的，就是来表达下，真优秀

### ISSUE THREAD

**Issue by cmlanche** [fresns/fresns#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

整体都体验了下，非常现代化，加油！

**Comment by cmlanche** [comment]
如果早几年出的话，我的网站w2solo.com就会采用你了

**Comment by jevantang** [comment]
感谢支持。有新项目用到了，欢迎使用。

**Comment by cmlanche** [comment]
话说你们的提交数都高达2000了，为什么star数这么少，应该早火了🔥

**Comment by jevantang** [comment]
我还没有宣传，这个月底我会用这个程序搭建一个针对互联网从业者的资讯社区，然后才会开始宣传。
https://tangjie.me/blog/278.html

**Comment by cmlanche** [comment]
> 我还没有宣传，这个月底我会用这个程序搭建一个针对互联网从业者的资讯社区，然后才会开始宣传。 https://tangjie.me/blog/278.html

能否在我们社区宣传下
https://w2solo.com/

**Comment by cmlanche** [comment]
> 我还没有宣传，这个月底我会用这个程序搭建一个针对互联网从业者的资讯社区，然后才会开始宣传。 https://tangjie.me/blog/278.html

我已经设置了允许新手发帖，你可以发个帖子，我设置精华，帮你推广下，有兴趣的话，我拉你进我们的solo Product 高级产品群

**Comment by jevantang** [comment]
> > 我还没有宣传，这个月底我会用这个程序搭建一个针对互联网从业者的资讯社区，然后才会开始宣传。 https://tangjie.me/blog/278.html
> 
> 我已经设置了允许新手发帖，你可以发个帖子，我设置精华，帮你推广下，有兴趣的话，我拉你进我们的solo Product 高级产品群

好的，我的微信在这里
https://docs.fresns.cn/community/sponsor.html#%E8%81%94%E7%B3%BB%E6%96%B9%E5%BC%8F
