### ISSUE TITLE
3.0 增加后台增加 APP下载设置

### ISSUE THREAD

**Issue by Naruto2018** [fresns/fresns#25]
3.0 增加后台增加 APP下载设置

可以设置 APP下载地址。。 IOS的话 可以支持1下 创建plist

**Comment by jevantang** [comment]
> IOS的话 可以支持1下 创建plist

没理解这句话，什么 plist？

**Comment by jevantang** [comment]
2.19.0 版本在下周发布，到时会完成该功能。

版本和 Apple App Site Association
