### ISSUE TITLE
用户昵称显示css建议

### ISSUE THREAD

**Issue by tony-studio** [fresns/fresns#27]
![图片](https://github.com/fresns/fresns/assets/60637421/03a5f57f-9b6f-4d42-81d0-91a7f50100a3)
目前帖子列表中，用户昵称显示区域使用 max-width 限制宽度，但值偏小，昵称的完整性和多样性考虑不足。

建议：fresns.css -> .user-link .user-nickname -> max-width: **10rem**; **text-overflow: ellipsis;** 使超出的部分以省略号显示。

![图片](https://github.com/fresns/fresns/assets/60637421/93abc7cc-5dfd-41fb-b85f-0957d4f88830)

**Comment by jevantang** [comment]
下一版加长了这里的限制。

在代码里，给插件预留了位置，所以限制了宽度，避免插件使用后导致换行。
