### ISSUE TITLE
扩展功能信息 是否能单独 弄个接口

### ISSUE THREAD

**Issue by Naruto2018** [fresns/fresns#31]
扩展功能信息 是否能单独 弄个接口
参数 fskey 根据fskey获取扩展信息
参数 useto 根据用途获取扩展列表

**Comment by jevantang** [comment]
https://docs.fresns.com/zh-Hans/clients/api/common/callback.html
https://docs.fresns.com/zh-Hans/clients/api/common/cmd-word.html
