### ISSUE TITLE
[bug]数据库索引重复

### ISSUE THREAD

**Issue by haoziluo** [fresns/fresns#38]
Schema::create('extends', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('eid', 32)->unique('eid');
            $table->unsignedTinyInteger('type')->default(1);
            $table->unsignedBigInteger('user_id')->index('extend_user_id');
            $table->string('app_fskey', 64);
            $table->string('url_parameter', 128)->nullable();
            $table->unsignedBigInteger('image_file_id')->nullable();
            $table->string('image_file_url')->nullable();
            switch (config('database.default')) {
                case 'pgsql':
                    $table->jsonb('content')->nullable();
                    $table->jsonb('action_items')->nullable();
                    break;

                default:
                    $table->json('content')->nullable();
                    $table->json('action_items')->nullable();
            }
            $table->unsignedTinyInteger('view_position')->default(2);
            $table->unsignedTinyInteger('view_type')->default(1);
            $table->boolean('is_enabled')->default(1);
            $table->timestamp('ended_at')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->nullable();
            $table->softDeletes();
        });

        Schema::create('extend_users', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('extend_id')->index('extend_id');
            $table->unsignedBigInteger('user_id')->index('extend_user_id');
            $table->string('action_key', 64)->nullable()->index('extend_action_key');
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->nullable();
            $table->softDeletes();
        });

这里extend_user_id索引名重复了

**Comment by jevantang** [comment]
感谢反馈，下一版修复
