### ISSUE TITLE
多次尝试安装失败，宝塔一键部署后，404，有时候是500

### ISSUE THREAD

**Issue by esncy** [fresns/fresns#40]
![image](https://github.com/user-attachments/assets/bc90e341-06bb-4600-808e-bd75c6a8c66f)
宝塔一键部署后，404，有时候是500
就尝试在宝塔的代码环境安装，也不成功，如上图。
请教什么原因呢？
CENTOS INGIX+MYSQL5.7+PHP8.3，其它环境要求的函数都好了，扩展支持也加了。

**Comment by jevantang** [comment]
答案就在明面上，你截图里不是写了。

symlink 函数问题，请启用 symlink 函数

**Comment by esncy** [comment]
> symlink
问题就出在这里，这个函数是启用状态。
![2](https://github.com/user-attachments/assets/28989cf8-09fc-4767-858c-0432adf9b9dd)

![2](https://github.com/user-attachments/assets/dfdbe383-41da-46ed-97db-af1f30682289)

**Comment by jevantang** [comment]
与我解释没有用的，你的机器说了是什么问题，你是信自己判断，还是信机器报错？

你现在用到的功能是程序框架功能，还不涉及我的程序。

**Comment by jevantang** [comment]
你使用的是终端中安装 Fresns 吗？

你这个问题，有可能是宝塔多 PHP 环境的问题。当你安装多个 PHP 时，终端中可能使用的不是 PHP-8.3 版本。

**Comment by jolly90s** [comment]
你是不是只安装了后端，没安装客户端，安装完后，要在域名后面输入/install

**Comment by mouyong** [comment]
删除后有重启一下 php-fpm 吗，没有的话可能会识别不到禁用函数已移除

**Comment by jevantang** [comment]
> ![image](https://private-user-images.githubusercontent.com/60813831/370986287-bc90e341-06bb-4600-808e-bd75c6a8c66f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNzQzMzcsIm5iZiI6MTczNDM3NDAzNywicGF0aCI6Ii82MDgxMzgzMS8zNzA5ODYyODctYmM5MGUzNDEtMDZiYi00NjAwLTgwOGUtYmQ3NWM2YThjNjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDE4MzM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZGZhNDJjNDgwMzc1OWI0ZDQ2MDFhOGQzZjgxYjk1NmUzNmE0OGJmYjE0MjIzNWZmOTQ3OWZmYTU4ZTY1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N_mnmwjmsBag1YvWRzKglZZ1aHVb8U8q4fTsODmUNrM) 宝塔一键部署后，404，有时候是500 就尝试在宝塔的代码环境安装，也不成功，如上图。 请教什么原因呢？ CENTOS INGIX+MYSQL5.7+PHP8.3，其它环境要求的函数都好了，扩展支持也加了。

你使用的是终端中安装 Fresns，有可能是宝塔多个 PHP 环境的问题。
当你安装多个 PHP 时，终端中可能使用的不是 PHP-8.3 版本。

在终端中执行 `php -v` 查看是哪个版本。
