### ISSUE TITLE
Composer 为2.5.1，但仍提示Composer 版本要求 2.3 或以上

### ISSUE THREAD

**Issue by soundghost** [fresns/fresns#5]
oneinstack环境，php 8.0.2,在基础环境检查那一步只有composer检测这里是红色。
但我的composer已经是官方2.5.1版本，删除后重新在官方用命令重新安装了composer依然还是卡在这里。

请问有何解决办法？

**Comment by jevantang** [comment]
你使用 composer 安装，首先要确定是安装的 2.x 版本。因为现在还是测试版，所以不能直接用安装命令，否则安装的是 1.x 旧版。

应该用这个 `composer create-project --prefer-dist fresns/fresns test --stability=beta`

其次如果安装流程中检测不到 composer 可以先跳过，安装后可以在仪表盘再检测查看。

**Comment by soundghost** [comment]
谢谢，已解决
