### ISSUE TITLE
Cannot connect to marketplace

### ISSUE THREAD

**Issue by jayabie** [fresns/fresns#6]
I can't connect to marketplace.

**Comment by jevantang** [comment]
Please wait for the deployment to go live next week.

**Comment by phpuiux** [comment]
> Пожалуйста, дождитесь начала развертывания на следующей неделе.

Add a visual editor editorjs. 🫶

**Comment by jevantang** [comment]
> > Пожалуйста, дождитесь начала развертывания на следующей неделе.
> 
> Add a visual editor editorjs. 🫶

The default theme template is lightly edited and does not support rich text. However, an editor plugin can be installed to enable rich text (markdown) publishing.

**Comment by phpuiux** [comment]
> > > Пожалуйста, дождитесь начала развертывания на следующей неделе.
> > 
> > 
> > Add a visual editor editorjs. 🫶
> 
> The default theme template is lightly edited and does not support rich text. However, an editor plugin can be installed to enable rich text (markdown) publishing.

![image](https://user-images.githubusercontent.com/2655626/229453249-e248187b-ed89-4e42-b471-6b7fdbaa4d9c.png)

**Comment by jevantang** [comment]
> > > > Пожалуйста, дождитесь начала развертывания на следующей неделе.
> > > 
> > > 
> > > Add a visual editor editorjs. 🫶
> > 
> > 
> > The default theme template is lightly edited and does not support rich text. However, an editor plugin can be installed to enable rich text (markdown) publishing.
> 
> ![image](https://user-images.githubusercontent.com/2655626/229453249-e248187b-ed89-4e42-b471-6b7fdbaa4d9c.png)

Fixed, not yet release
https://github.com/fresns/fresns/blob/2.x/app/Models/Account.php#L29

**Comment by jevantang** [comment]
> > > > Пожалуйста, дождитесь начала развертывания на следующей неделе.
> > > 
> > > 
> > > Add a visual editor editorjs. 🫶
> > 
> > 
> > The default theme template is lightly edited and does not support rich text. However, an editor plugin can be installed to enable rich text (markdown) publishing.
> 
> ![image](https://user-images.githubusercontent.com/2655626/229453249-e248187b-ed89-4e42-b471-6b7fdbaa4d9c.png)

Fixed, please download [Fresns v2.8](https://fresns.org/guide/install.html#download)
