### ISSUE TITLE
file .env is not intact after  installing via composer

### ISSUE THREAD

**Issue by deloz** [fresns/fresns#9]
**Fresns Version**
v2.10.2

**Describe the bug**

1. `PHP Warning:  copy(.env.example): Failed to open stream: No such file or directory in Command line code on line 1`
2. `.env` is not intact

**To Reproduce**
1. running command `composer create-project fresns/fresns`

**Expected behavior**
the installation  via composer is without PHP warnings and the `.env` file is intact

**Screenshots**
[![asciicast](https://asciinema.org/a/jAmlQAfDM6xugcBIfxYzHNZEA.svg)](https://asciinema.org/a/jAmlQAfDM6xugcBIfxYzHNZEA)

**Desktop (please complete the following information):**
 - OS: CentOS 7.29
 - Browser:
 - Version

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**
none

**Comment by jevantang** [comment]
Once you have configured the web service, please install fresns visually, the complete .env is configured in the visualisation.

https://fresns.org/guide/install.html#_2-install-config

**Comment by jevantang** [comment]
Version 2.11 supports installation in view or terminal
Terminal command: `php artisan fresns:install`

https://fresns.org/guide/install.html#installing
